### ISSUE TITLE
modify no-unused-expressions

### ISSUE THREAD

**Issue by Jarrku** [Moovly/eslint-config-moovly#10]
allowing shortCircuit and ternary enables you to call functions without return values using a ternary or shortCircuit expression. Without these exceptions the expressions gets flagged as unused which is not the case.

```json
no-unused-expressions: ["error", { "allowShortCircuit": true, "allowTernary": true }]
```

**Comment by m4nuC** [comment]
Looks sensible, go ahead and add it
