### ISSUE TITLE
Loosen jsx-a11y/label-has-for

### ISSUE THREAD

**Issue by Jarrku** [Moovly/eslint-config-moovly#11]
[jsx-a11y/label-has-for](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-for.md) is really strict at the moment. It requires both the input nested inside the label and a htmlFor on the label.

I suggest to loosen it to only require the htmlFor/id pair as styling gets messed up when you have to nest it inside the labels.

Changed rule:
```json
    "jsx-a11y/label-has-for": [
      2,
      {
        "required": "id",
        "allowChildren": false
      }
    ]
```

**Comment by mrjpsilver** [comment]
I'd like to have:
```
    "jsx-a11y/label-has-for": [
      2,
      {
        "required": "id",
        "allowChildren": true
      }
    ]
```

I have a new wrapper for `<input/>` elements that creates a Bootstrap-compliant `form-group` including a label. It utilizes `{children}`.

**Comment by Jarrku** [comment]
Also works for me, just copied the rule and only changed the required option :)
