### ISSUE TITLE
Use "env" setting instead of "global"

### ISSUE THREAD

**Issue by Jarrku** [Moovly/eslint-config-moovly#2]
Use the "env" setting to correctly configure all the globals from the environments we're using instead of relying on adding them all manually to "global".

[List of all environments](https://eslint.org/docs/user-guide/configuring#specifying-environments)

Recommended envs for now:
```json
    "env": {
        "browser": true,
        "jest": true,
        "jquery": true,
    }
```

This reduces "globals" to:
```json
 "globals": {
    "PIXI": true
  }
```

The "settings" webpack config and the PIXI global are also not true for all environments and I think this should be left open for the project specific ESLint file.

**Comment by m4nuC** [comment]
👍 updating
