### ISSUE TITLE
Disable "react/require-default-props"

### ISSUE THREAD

**Issue by Jarrku** [Moovly/eslint-config-moovly#5]
[require-default-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-default-props.md) is unfeasable at the moment I think till we clear up stuff, but I do think its valuable to be able to mark that you're not guaranteed to receive all props.
```json
{
  "react/require-default-props": 0
}
```

**Comment by m4nuC** [comment]
added
