### ISSUE TITLE
Change to "react/sort-comp"

### ISSUE THREAD

**Issue by Jarrku** [Moovly/eslint-config-moovly#6]
[sort-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md) is useful to bring a set structure to the components, but I think instance variables should appear above lifecycle methods. 

```json
"react/sort-comp": [1,  { "order": [
    "static-methods",
    "instance-variables",
    "lifecycle",
    "everything-else",
    "render"
  ]}]
```

Provided options (You can create custom groups as well if needed):
* `static-methods` is a special keyword that refers to static class methods.
* `lifecycle` is referring to the lifecycle group defined in groups.
* `everything-else` is a special group that match all the methods that do not match any of the other groups.
* `render` is referring to the render method.
* `type-annotations`. This group is not specified by default, but can be used to enforce flow annotations positioning.
* `getters` This group is not specified by default, but can be used to enforce class getters positioning.
* `setters` This group is not specified by default, but can be used to enforce class setters positioning.
* `instance-variables` This group is not specified by default, but can be used to enforce all other instance variables positioning.
* `instance-methods` This group is not specified by default, but can be used to enforce all other instance methods positioning.

**Comment by m4nuC** [comment]
added
