### ISSUE TITLE
Enforce max-len

### ISSUE THREAD

**Issue by Jarrku** [Moovly/eslint-config-moovly#7]
Enforcing a [max-len](https://eslint.org/docs/rules/max-len) does seem useful to me to make the code not too wide and readable on different screen sizes.

The airbnb rule of 100 could be expended to 150 though in my opinion.

**Default airbnb rule:**
max-len: ["error", { "code": 80, "tabWidth": 4 }]

```json
 max-len: ["error", 100, 2, {
      "ignoreUrls": true,
      "ignoreComments": false,
      "ignoreRegExpLiterals": true,
      "ignoreStrings": true,
      "ignoreTemplateLiterals": true,
    }]
```
**Recommended change:**
 max-len: ['error', **150, 4**]
Changes tabsize to 4 spaces in accordance with indent size and increases the limit to 150.
Exceptions can be discussed as well.
```json
 max-len: ["error", 150, 4, {
      "ignoreUrls": true,
      "ignoreComments": false,
      "ignoreRegExpLiterals": true,
      "ignoreStrings": true,
      "ignoreTemplateLiterals": true,
    }]
```

**Comment by m4nuC** [comment]
added
