### ISSUE TITLE
no-unused-vars

### ISSUE THREAD

**Issue by Jarrku** [Moovly/eslint-config-moovly#8]
[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars) is currently enabled with these settings:

```json
{
    "no-unused-vars": ["error", { "vars": "all", "args": "after-used", "ignoreRestSiblings": true }]
}
```

Personally I'm for reducing args in the code when they are unused but it might be helpful to keep them in the function signature if they get passed to the function anyway. Changed rule would then be: 
```json
{
    "no-unused-vars": ["error", { "vars": "all", "args": "none", "ignoreRestSiblings": true }]
}
```

**Comment by m4nuC** [comment]
added
